# Generated by Django 3.0.3 on 2020-02-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_admin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(choices=[('Ag', 'Agriculture'), ('Pe', 'Personal'), ('Ca', 'Capital'), ('Ra', 'Ratio')], max_length=20)),
                ('category', models.CharField(choices=[('In', 'Individual'), ('Or', 'Organisation'), ('Co', 'Country'), ('Cr', 'CreditHistory'), ('Lo', 'Loan')], max_length=20)),
                ('characteristic', models.CharField(choices=[('Ag', 'Age'), ('In', 'Income'), ('Ge', 'Gender')], max_length=20)),
                ('colour', models.CharField(choices=[('Gr', 'Green'), ('Am', 'Amber'), ('Re', 'Red')], max_length=20)),
            ],
        ),
    ]
